sonar.projectKey=super_otonom
sonar.projectName=super_otonom
sonar.projectVersion=7.0.0
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.exclusions=**/test_*.py,**/tests/**
