"""VR-24: Model validation due-date checker.

Scans MODEL_INVENTORY.md for models whose next validation date is
within 30 days (or overdue).  When running in CI with --ci flag,
auto-opens a GitHub issue for each overdue / upcoming model.

Exit codes:
  0  — all models have > 30 days until next validation
  1  — at least one model is due within 30 days or overdue
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import List, Optional, Sequence

model_validation_governance_active = True

_ROOT = Path(__file__).resolve().parents[1]
_INVENTORY = _ROOT / "docs" / "MODEL_INVENTORY.md"

_TABLE_ROW = re.compile(
    r"^\|\s*(?P<model_id>MR-[\w-]+)\s*\|"
    r"\s*(?P<name>[^|]+)\s*\|"
    r"\s*(?P<vr>VR-\d+)\s*\|"
    r"\s*(?P<module>[^|]+)\s*\|"
    r"\s*(?P<type>[^|]+)\s*\|"
    r"\s*(?P<developer>[^|]+)\s*\|"
    r"\s*(?P<validator>[^|]+)\s*\|"
    r"\s*(?P<last_validated>\d{4}-\d{2}-\d{2})\s*\|"
    r"\s*(?P<next_due>\d{4}-\d{2}-\d{2})\s*\|"
    r"\s*(?P<status>[^|]+)\s*\|",
)


@dataclass(frozen=True)
class ModelEntry:
    model_id: str
    name: str
    vr: str
    module: str
    model_type: str
    developer: str
    validator: str
    last_validated: date
    next_due: date
    status: str

    @property
    def developer_equals_validator(self) -> bool:
        d = self.developer.strip().lower()
        v = self.validator.strip().lower()
        return d == v and d != ""


@dataclass(frozen=True)
class ValidationAlert:
    model_id: str
    name: str
    next_due: date
    days_remaining: int
    overdue: bool
    governance_violation: bool


def parse_inventory(path: Optional[Path] = None) -> List[ModelEntry]:
    p = path or _INVENTORY
    if not p.is_file():
        return []
    text = p.read_text(encoding="utf-8")
    entries: List[ModelEntry] = []
    for line in text.splitlines():
        m = _TABLE_ROW.match(line)
        if not m:
            continue
        entries.append(
            ModelEntry(
                model_id=m.group("model_id").strip(),
                name=m.group("name").strip(),
                vr=m.group("vr").strip(),
                module=m.group("module").strip(),
                model_type=m.group("type").strip(),
                developer=m.group("developer").strip(),
                validator=m.group("validator").strip(),
                last_validated=date.fromisoformat(m.group("last_validated").strip()),
                next_due=date.fromisoformat(m.group("next_due").strip()),
                status=m.group("status").strip(),
            )
        )
    return entries


def check_due(
    entries: List[ModelEntry],
    *,
    today: Optional[date] = None,
    warn_days: int = 30,
) -> List[ValidationAlert]:
    ref = today or date.today()
    alerts: List[ValidationAlert] = []
    for e in entries:
        if e.status.lower() not in ("active", "conditional"):
            continue
        days_remaining = (e.next_due - ref).days
        overdue = days_remaining < 0
        governance_violation = e.developer_equals_validator
        if days_remaining <= warn_days or governance_violation:
            alerts.append(
                ValidationAlert(
                    model_id=e.model_id,
                    name=e.name,
                    next_due=e.next_due,
                    days_remaining=days_remaining,
                    overdue=overdue,
                    governance_violation=governance_violation,
                )
            )
    return alerts


def _open_github_issue(alert: ValidationAlert) -> bool:
    if alert.overdue:
        title = f"[OVERDUE] Model validation: {alert.model_id} ({alert.name})"
        body = (
            f"Model **{alert.model_id}** ({alert.name}) validation was due on "
            f"{alert.next_due.isoformat()} and is **{abs(alert.days_remaining)} days overdue**.\n\n"
            f"Please schedule independent validation immediately.\n\n"
            f"_Auto-generated by `check_model_validation_due.py` (VR-24)_"
        )
    elif alert.governance_violation:
        title = f"[GOVERNANCE] Model {alert.model_id}: developer == validator"
        body = (
            f"Model **{alert.model_id}** ({alert.name}) has the same person assigned as "
            f"both developer and validator. This violates the independence rule.\n\n"
            f"Please assign a different validator.\n\n"
            f"_Auto-generated by `check_model_validation_due.py` (VR-24)_"
        )
    else:
        title = f"[DUE SOON] Model validation: {alert.model_id} — {alert.days_remaining}d remaining"
        body = (
            f"Model **{alert.model_id}** ({alert.name}) validation is due on "
            f"{alert.next_due.isoformat()} ({alert.days_remaining} days remaining).\n\n"
            f"Please schedule independent validation.\n\n"
            f"_Auto-generated by `check_model_validation_due.py` (VR-24)_"
        )
    try:
        subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--body",
                body,
                "--label",
                "risk,model-validation",
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return False


def format_report(alerts: List[ValidationAlert]) -> str:
    if not alerts:
        return "All models have valid validation dates. No action required."
    lines = ["Model Validation Status Report", "=" * 40, ""]
    for a in sorted(alerts, key=lambda x: x.days_remaining):
        tag = "OVERDUE" if a.overdue else "DUE SOON"
        if a.governance_violation:
            tag = "GOVERNANCE"
        lines.append(
            f"[{tag}] {a.model_id} ({a.name}): "
            f"due {a.next_due.isoformat()}, {a.days_remaining}d remaining"
        )
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description="Check model validation due dates (VR-24).")
    p.add_argument("--ci", action="store_true", help="Auto-open GitHub issues for alerts")
    p.add_argument("--json", action="store_true", help="JSON output")
    p.add_argument("--warn-days", type=int, default=30, help="Warning threshold in days")
    p.add_argument("--date", type=str, default=None, help="Override today (YYYY-MM-DD)")
    args = p.parse_args(list(argv) if argv is not None else None)

    today = date.fromisoformat(args.date) if args.date else None
    entries = parse_inventory()
    if not entries:
        print("ERROR: No models found in MODEL_INVENTORY.md")
        return 1

    alerts = check_due(entries, today=today, warn_days=args.warn_days)

    governance_violations = [a for a in alerts if a.governance_violation]
    if governance_violations:
        for gv in governance_violations:
            print(f"GOVERNANCE VIOLATION: {gv.model_id} — developer == validator")

    if args.json:
        payload = {
            "ok": len(alerts) == 0,
            "total_models": len(entries),
            "alerts": [
                {
                    "model_id": a.model_id,
                    "name": a.name,
                    "next_due": a.next_due.isoformat(),
                    "days_remaining": a.days_remaining,
                    "overdue": a.overdue,
                    "governance_violation": a.governance_violation,
                }
                for a in alerts
            ],
        }
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    else:
        print(format_report(alerts))

    if args.ci and alerts:
        for a in alerts:
            ok = _open_github_issue(a)
            status = "opened" if ok else "FAILED"
            print(f"  GitHub issue {status}: {a.model_id}")

    return 0 if not alerts else 1


if __name__ == "__main__":
    raise SystemExit(main())
