"""Stressed VaR — Basel 2.5 stress-period rescaling (VR-11).

For each candidate stress period the engine computes
``historical_var(stress_returns, 0.99)`` and rescales by
``σ_current / σ_stress`` so the result reflects the *current* volatility
regime projected onto the worst historical episode.

Limit rule:  ``stressed_var > 2 × var_99  →  emergency_stop('stressed_var_breach')``
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from super_otonom.risk.var_models import historical_var

# ── Canonical crypto stress periods ─────────────────────────────────────────
STRESS_PERIODS: List[Tuple[str, str]] = [
    ("2020_covid", "COVID-19 March 2020"),
    ("2021_china_ban", "China Mining Ban May-Jun 2021"),
    ("2022_luna", "LUNA/UST Collapse May 2022"),
    ("2022_ftx", "FTX Collapse Nov 2022"),
    ("2024_yen_carry", "Yen Carry Trade Unwind Aug 2024"),
]

# ── Forward-looking hypothetical scenarios ──────────────────────────────────
FORWARD_LOOKING_SCENARIOS: List[Tuple[str, str]] = [
    ("hypothetical_btc_70pct_crash", "BTC 70% crash in 48h"),
    ("hypothetical_usdt_full_depeg", "USDT full de-peg to $0.80"),
    ("hypothetical_global_exchange_halt", "Global exchange halt 72h"),
    ("hypothetical_regulatory_ban", "Major jurisdiction crypto ban"),
]

SVAR_MIN_OBS = 20
"""Minimum observations per stress period to include in computation."""

_FIXTURES = Path(__file__).resolve().parent / ".." / ".." / "tests" / "risk" / "fixtures"

# Sentinel for var_topology detection
stressed_var_engine = True


@dataclass(frozen=True)
class StressedVarResult:
    """Stressed VaR computation output."""

    stressed_var: float = 0.0
    worst_period: str = ""
    per_period_var: Dict[str, float] = field(default_factory=dict)
    rescale_factor: float = 1.0
    breach: bool = False
    breach_multiplier: float = 2.0


class StressedVaR:
    """Basel 2.5 Stressed VaR engine.

    For each stress period *p*:

        sVaR_p = historical_var(stress_p, conf) × (σ_current / σ_stress_p)

    Final:  ``stressed_var = max(sVaR_p)``
    """

    def __init__(
        self,
        stress_returns: Dict[str, Sequence[float]],
    ) -> None:
        self._stress_returns: Dict[str, List[float]] = {
            k: [float(x) for x in v] for k, v in stress_returns.items()
        }

    @classmethod
    def from_fixture(
        cls,
        path: Optional[Path] = None,
        *,
        include_forward_looking: bool = False,
    ) -> "StressedVaR":
        """Load stress-period returns from the JSON fixture.

        Parameters
        ----------
        path:
            Path to historical stress fixture. Defaults to test fixtures.
        include_forward_looking:
            When *True*, also adds hypothetical forward-looking scenarios
            generated by :func:`generate_hypothetical_returns`.
        """
        if path is None:
            path = _FIXTURES / "historical_stress_returns.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        stress_dict = {k: v["returns"] for k, v in data.items()}

        if include_forward_looking:
            stress_dict.update(generate_hypothetical_returns())

        return cls(stress_dict)

    # ── Primary interface ───────────────────────────────────────────────────

    def compute(
        self,
        current_returns: Sequence[float],
        conf: float = 0.99,
        *,
        breach_multiplier: float = 2.0,
        var_99_for_limit: Optional[float] = None,
    ) -> StressedVarResult:
        """Compute rescaled stressed VaR across all loaded stress periods.

        Parameters
        ----------
        current_returns:
            Recent portfolio returns (typically last 60 days).
        conf:
            Confidence level (default 0.99 per Basel 2.5).
        breach_multiplier:
            Trigger ratio vs ``var_99_for_limit``.
        var_99_for_limit:
            Current VaR(99%) for breach check.  If *None* breach is always False.
        """
        cur = np.asarray(current_returns, dtype=float).ravel()
        if len(cur) < 2:
            return StressedVarResult()

        sigma_current = float(np.std(cur, ddof=1))

        per_period: Dict[str, float] = {}
        worst_key = ""
        worst_val = 0.0
        worst_rescale = 1.0

        for key, rets in self._stress_returns.items():
            if len(rets) < SVAR_MIN_OBS:
                continue

            raw_var = historical_var(rets, conf, horizon_days=1)
            sigma_stress = float(np.std(rets, ddof=1))

            if sigma_stress < 1e-12:
                per_period[key] = raw_var
                if raw_var > worst_val:
                    worst_val = raw_var
                    worst_key = key
                    worst_rescale = 1.0
                continue

            rescale = sigma_current / sigma_stress
            scaled = raw_var * rescale
            per_period[key] = scaled

            if scaled > worst_val:
                worst_val = scaled
                worst_key = key
                worst_rescale = rescale

        # ── Breach check ────────────────────────────────────────────────────
        ref = var_99_for_limit if var_99_for_limit is not None else 0.0
        breach = (worst_val > breach_multiplier * ref) if ref > 0 else False

        return StressedVarResult(
            stressed_var=worst_val,
            worst_period=worst_key,
            per_period_var=per_period,
            rescale_factor=worst_rescale,
            breach=breach,
            breach_multiplier=breach_multiplier,
        )

    # ── Convenience ─────────────────────────────────────────────────────────

    @staticmethod
    def check_limit(
        stressed_var: float,
        var_99: float,
        multiplier: float = 2.0,
    ) -> bool:
        """Return *True* when stressed VaR exceeds the limit multiple."""
        if var_99 <= 0:
            return False
        return stressed_var > multiplier * var_99

    @property
    def period_keys(self) -> List[str]:
        return sorted(self._stress_returns.keys())

    @property
    def historical_period_keys(self) -> List[str]:
        """Keys for historical (backward-looking) stress periods only."""
        hist = {k for k, _ in STRESS_PERIODS}
        return sorted(k for k in self._stress_returns if k in hist)

    @property
    def forward_looking_period_keys(self) -> List[str]:
        """Keys for hypothetical (forward-looking) stress periods only."""
        fwd = {k for k, _ in FORWARD_LOOKING_SCENARIOS}
        return sorted(k for k in self._stress_returns if k in fwd)


# ── Forward-looking scenario generators ─────────────────────────────────────

def generate_hypothetical_returns(seed: int = 2025) -> Dict[str, List[float]]:
    """Generate synthetic returns for all forward-looking hypothetical scenarios.

    Each scenario models a plausible extreme event with calibrated
    volatility, drawdown profile, and partial recovery.
    """
    rng = np.random.RandomState(seed)
    scenarios: Dict[str, List[float]] = {}

    # 1. BTC 70% crash in 48h — cascading liquidations
    #    Day 1: -35%, Day 2: -35% (compound → ~58% total),
    #    then volatile recovery over 28 days
    btc_crash = []
    btc_crash.append(-0.35)
    btc_crash.append(-0.35)
    for _ in range(28):
        btc_crash.append(rng.normal(-0.02, 0.08))
    scenarios["hypothetical_btc_70pct_crash"] = btc_crash

    # 2. USDT full de-peg to $0.80 — stablecoin confidence crisis
    #    Gradual depeg over 5 days, USDT pairs collapse, alts crash
    depeg = []
    for day in range(5):
        depeg.append(rng.normal(-0.04 * (day + 1), 0.03))
    for _ in range(25):
        depeg.append(rng.normal(-0.03, 0.06))
    scenarios["hypothetical_usdt_full_depeg"] = depeg

    # 3. Global exchange halt 72h — all major CEXs offline
    #    3 days zero returns (frozen), then violent repricing
    halt = [0.0, 0.0, 0.0]
    halt.append(-0.25)  # repricing shock
    for _ in range(26):
        halt.append(rng.normal(-0.015, 0.07))
    scenarios["hypothetical_global_exchange_halt"] = halt

    # 4. Major jurisdiction regulatory ban
    #    Announcement shock + sustained selling over weeks
    ban = [-0.20]  # announcement day
    for _ in range(29):
        ban.append(rng.normal(-0.015, 0.04))
    scenarios["hypothetical_regulatory_ban"] = ban

    return scenarios


def compute_stressed_var(
    current_returns: Sequence[float],
    stress_returns: Dict[str, Sequence[float]],
    conf: float = 0.99,
) -> Tuple[float, str, Dict[str, float]]:
    """Convenience: ``(stressed_var, worst_period, per_period_var)``."""
    engine = StressedVaR(stress_returns)
    r = engine.compute(current_returns, conf)
    return r.stressed_var, r.worst_period, r.per_period_var
